version: "3.7"
services:
  db:
    # image: mysql:8.0
    platform: linux/amd64
    build: ./mysql/
    container_name: mysql_3sem
    restart: unless-stopped 
    
    environment:
      MYSQL_ROOT_PASSWORD: "MYSQL_SECRET_ROOT_PASSWORD"
      TZ: "Europe/Copenhagen"
    ports:
      # <Port exposed> : < MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'

      # Where our data will be persisted
    volumes:
      - ./data:/var/lib/mysql # for data
      - ./scripts:/scripts
      - ./mysql/startscript:/docker-entrypoint-initdb.d
    networks:
      -  virtual_network1

  web:
    # image:  tomcat:9.0.37-jdk8
    platform: linux/amd64
    build: ./tomcat/
    container_name: tomcat_3sem
    restart: unless-stopped

    # ---- IMPORTANT ----
    # In production (on digitalOcean)  replace ALL values below with your own secret values
    # NEVER COMMIT/PUSH this file/project
    environment:
      CONNECTION_STR: "jdbc:mysql://db:3306/" # the database is set in the pom.xml file for each project
      USER: "dev" # database user to use in tomcat apps
      PW: "ax2" # database password
      DEPLOYED: "PROD"

    ports:
     - "8081:8080"
    volumes:
      - ./tomcat/webapps:/usr/local/tomcat/webapps
      - ./tomcat/tomcat-users.xml:/usr/local/tomcat/conf/tomcat-users.xml

 
    networks:
      -  virtual_network1
    
      # copy the tomcat manager app, context.xml and start tomcat)
    command: sh -c "cp -r /usr/local/tomcat/webapps.dist/manager /usr/local/tomcat/webapps && cp /tmp/context.xml /usr/local/tomcat/webapps/manager/META-INF/context.xml && catalina.sh run"
    
networks:
  virtual_network1:
    driver: bridge

# bridge: The default network driver. If you don’t specify a driver, this is the type of network you are creating. Bridge networks are usually used when your applications run in standalone containers that need to communicate. See bridge networks.
